/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package textbookcatalogue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAController() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.controller, "app should have a controller");
    }
}
